// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ciFL56DxZl24F3kEimh0Hkt54j_A1vc',
    appId: '1:88700249411:web:5b30b6100b4e34fcd6bbf6',
    messagingSenderId: '88700249411',
    projectId: 'fir-ti-a70af',
    authDomain: 'fir-ti-a70af.firebaseapp.com',
    storageBucket: 'fir-ti-a70af.firebasestorage.app',
    measurementId: 'G-HEB78RCJ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX-d7CPPguatJ9n8rcZL83tUWe58r7Qiw',
    appId: '1:88700249411:android:d1e40f7c3c837f3ed6bbf6',
    messagingSenderId: '88700249411',
    projectId: 'fir-ti-a70af',
    storageBucket: 'fir-ti-a70af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8cj1GSjAgoE6duQ8sg4IYKQF-oIJOZg',
    appId: '1:88700249411:ios:8f7cd3513ddab623d6bbf6',
    messagingSenderId: '88700249411',
    projectId: 'fir-ti-a70af',
    storageBucket: 'fir-ti-a70af.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN8cj1GSjAgoE6duQ8sg4IYKQF-oIJOZg',
    appId: '1:88700249411:ios:8f7cd3513ddab623d6bbf6',
    messagingSenderId: '88700249411',
    projectId: 'fir-ti-a70af',
    storageBucket: 'fir-ti-a70af.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ciFL56DxZl24F3kEimh0Hkt54j_A1vc',
    appId: '1:88700249411:web:ca220d21c0c2fb97d6bbf6',
    messagingSenderId: '88700249411',
    projectId: 'fir-ti-a70af',
    authDomain: 'fir-ti-a70af.firebaseapp.com',
    storageBucket: 'fir-ti-a70af.firebasestorage.app',
    measurementId: 'G-3NZ3VG3C9T',
  );
}
